### PR TITLE
Do not crash when reporting bad spelling in docstrings

### PR DESCRIPTION
**Pull request by pgerell**
Fix for issue #167

### CODE REVIEW

**Comment by ejd** [comment]
This PR fixes the issue I reported in #167.

**Comment by dhellmann** [comment]
This does look like it addresses the problem, but every consumer of the Checker would have to know to do the same conversion. I think I'd rather change the Checker so that it always returns a number for the offset. What do you think?

**Comment by pgerell** [comment]
I believe the checker always returns a number. The problem is that `docutils.utils.get_source_line(node)` sometimes returns `None`.
This happens for all `:param:` arguments in docstrings, not only ones without newlines. If the contents of the docstring is copied into a rst-file the node gets a line number.

**Comment by dhellmann** [comment]
> I believe the checker always returns a number. 

OK, I misunderstood the source of the bug.

**Review by dhellmann — APPROVED** [review]

**Comment by dhellmann** [comment]
This fix is included in release 7.4.1

**Pull request merged**
