### PR TITLE
Include all supported Pythons in the tox test matrix

### PR DESCRIPTION
**Pull request by jdufresne**
Make it easier to test all supported Pythons to help ensure changes
don't introduce incompatibilities.

### CODE REVIEW

**Review by dhellmann — APPROVED** [review]

**Comment by dhellmann** [comment]
I'm not sure what's going on with the import failure in that 3.6 test job. Have you been able to reproduce it locally?

**Comment by jdufresne** [comment]
I'm not sure either. I was a bit perplexed by that. I can't reproduce that locally, but I'm running Fedora not Ubuntu.

**Comment by jdufresne** [comment]
I have dropped Python 3.6 from Travis until the error can be better understood. This at least gets the PR to green. Python 3.6 is still in `tox.ini` so contributors wishing to run the full test matrix can continue to do so. WDYT about this approach?

**Comment by dhellmann** [comment]
That works for me. Do you know what platforms still default to 3.6? I don't know how strong the demand is anyway.

**Review by dhellmann — APPROVED** [review]
LGTM

**Comment by jdufresne** [comment]
Thanks.

> Do you know what platforms still default to 3.6?

Maybe some older LTS style platforms. I'm not aware of any that were recently released though.

**Pull request merged**
