### PR TITLE
add a verbose parameter

### LINKED ISSUE #122: is there a verbose options ?
I work on a rather big documentation and as my colleagues are not aware of .rst format they send me huge piece of doc in .docx, .txt, .md... It means that sometime I create in one batch thousands of lines with thousands of misspelled word (mainly Geospatial words that I need to add to the dictionary). So when I run the following command:

```
make spelling
```

I get an avalanche of output in my terminal. I'm very happy with the `spelling` folder created within the build directory and would just like to have the build information displayed in the terminal, not the content of the `.spelling` files. Is it already possible ? 

If not is it something you would consider as an enhancement ?

### PR DESCRIPTION
**Pull request by 12rambau**
Fix #122

### CODE REVIEW

**Comment by dhellmann** [comment]
The change is good, generally. It looks like the linter does not like some of the code formatting, and there's an issue with the documentation build. You can run those same jobs via `tox` locally.

**Comment by 12rambau** [comment]
I don't really understand why the number of character is limited but I reduced it to avoid linter complains. The documentation issue was linked to a typo.

**Comment by dhellmann** [comment]
I released this change as part of 7.2.1 a little while ago.

**Comment by 12rambau** [comment]
awesome thanks !

**Pull request merged**
